### ISSUE TITLE
Reproduce the OSLC008 error

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/lyo-adaptor-sample-modelling#13]
"OSLC008 OslcCoreMissingAnnotationException" is thrown by the Lyo Designer generated code when run with Jetty under Docker.

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=519475 for the old discussion.

**Comment by berezovskyi** [comment]
wontfix unless @jadelkhoury or @jamsden insist on moving this to Lyo

**Comment by jadelkhoury** [comment]
This is so old, I don't remember what it is about. Let's see if it reappears.
