### ISSUE TITLE
What RDF format data is required to create a resource?

### ISSUE THREAD

**Issue by BIT-masterpy** [OSLC/lyo-adaptor-sample-modelling#27]
**hi:

I want to create a new resource. Can you provide an example of RDF?
Like this:**

<rdf:RDF    
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:dcterms="http://purl.org/dc/terms/"    
   xmlns:foaf="http://xmlns.com/foaf/0.1/"    
   xmlns:oslc_blog="http://open-services.net/ns/bogus/blogs#">

   <oslc_blog:Entry
      rdf:about="http://example.com/blogs/entry/1">

      <dcterms:title>I love trash</dcterms:title>
      <dcterms:modified>2002-10-10T12:00:00-05:00</dcterms:modified>
      <dcterms:content>
         Anything dirty or dingy or dusty. 
         Anything ragged or rotten or rusty.
      </dcterms:content>
      <dcterms:creator>
         <foaf:Person>
             <foaf:name>Oscar T. Grouch</foaf:name>
         </foaf:Person>
      </dcterms:creator>

   </oslc_blog:Entry>

**Comment by jadelkhoury** [comment]
None of the 2 sample projects in this repository support the RDF structure you are giving as an example.
To see example of what resources are produced here, 

To see what Resource Shapes are supported for the adaptor-rm project, you can for example navigate to this page http://localhost:8081/adaptor-rm/services/resourceShapes/requirement.

To see example of RDF resources produced by the adaptor-rm project, do a GET request on the Query capability http://localhost:8081/adaptor-rm/services/requirements/query.
You can then pick a particular URI, and do a GET on that, to receive the RDF for a particualr Requirement.
Of course, you need to do that with Postman, where you can also specify the accept/content-type appropriatly

**Comment by berezovskyi** [comment]
You should use Lyo Client to generate RDF. RDF is not a format (model, strictly speaking) that is designed to be written by hand but instead generated by a library.

Please also look at http://oslc.github.io/developing-oslc-applications/technical-foundations.html and https://www.w3.org/TR/rdf11-primer/
