### ISSUE TITLE
Regenerate the webapps using the latest version of the plugin

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/lyo-adaptor-sample-modelling#3]
The webapps suffer from the bug with the creation factory URIs.

![image](https://user-images.githubusercontent.com/64734/27310100-3f305c8e-5558-11e7-8ec8-8785740671e5.png)

cc @jadelkhoury @jamsden

**Comment by jadelkhoury** [comment]
The fix is in oslc4j and not the generator. So are you sure you are running the latest version of the libraries
