### ISSUE TITLE
Testing adaptor uses old client

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/lyo-adaptor-sample-modelling#35]
on branch `4.0.0-snapshot`:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project adaptor-testing-webapp: Compilation failure: Compilation failure:
> [ERROR] /Users/andrew/kth/_misc/misc-lyo/adaptors/sample-modelling/adaptor-testing-webapp/src/main/java/com/sample/testing/clients/RequirementsAdaptorClient.java:[68,9] cannot find symbol
> [ERROR] symbol:   class OslcQueryParameters
> [ERROR] location: class com.sample.testing.clients.RequirementsAdaptorClient
> [ERROR] /Users/andrew/kth/_misc/misc-lyo/adaptors/sample-modelling/adaptor-testing-webapp/src/main/java/com/sample/testing/clients/RequirementsAdaptorClient.java:[68,51] cannot find symbol
> [ERROR] symbol:   class OslcQueryParameters
> [ERROR] location: class com.sample.testing.clients.RequirementsAdaptorClient
> [ERROR] /Users/andrew/kth/_misc/misc-lyo/adaptors/sample-modelling/adaptor-testing-webapp/src/main/java/com/sample/testing/clients/RequirementsAdaptorClient.java:[70,9] cannot find symbol
> [ERROR] symbol:   class OslcQuery
> [ERROR] location: class com.sample.testing.clients.RequirementsAdaptorClient
> [ERROR] /Users/andrew/kth/_misc/misc-lyo/adaptors/sample-modelling/adaptor-testing-webapp/src/main/java/com/sample/testing/clients/RequirementsAdaptorClient.java:[70,31] cannot find symbol
> [ERROR] symbol:   class OslcQuery
> [ERROR] location: class com.sample.testing.clients.RequirementsAdaptorClient
> [ERROR] /Users/andrew/kth/_misc/misc-lyo/adaptors/sample-modelling/adaptor-testing-webapp/src/main/java/com/sample/testing/clients/RequirementsAdaptorClient.java:[71,9] cannot find symbol
> [ERROR] symbol:   class OslcQueryResult
> [ERROR] location: class com.sample.testing.clients.RequirementsAdaptorClient
>

**Comment by jadelkhoury** [comment]
Not mentioning names, but someone cleaned up the package imports, which are then lost once code was regenerated. https://github.com/OSLC/lyo-adaptor-sample-modelling/commit/dcb169a4edd8e98a7571c416cc40e89bd1df84a6

**Comment by jadelkhoury** [comment]
Closed by https://github.com/OSLC/lyo-adaptor-sample-modelling/commit/d0a80403d9d0159d4ced9ceb2f897c3ba3c8e159

**Comment by berezovskyi** [comment]
😱 who could that be? my apologies!

**Comment by jadelkhoury** [comment]
I was going to be cool and let you commit code to this repo. Now I have to reconsider :-)
