### ISSUE TITLE
Fails Validation

### ISSUE THREAD

**Issue by andylapping** [OSLC/lyo-adaptor-sample-modelling#65]
O downloaded the zip and imported it into an existing Lyo Designer
Opened My.Toolchain and ran Validate:
![GitHubSample](https://user-images.githubusercontent.com/22616015/148533132-fe87cf32-20d7-4eb7-bd0f-7da22802584f.jpg)

**Comment by jadelkhoury** [comment]
Hi! 
These "required features" are deprecated. So the validation will fail, but in practice you won't have problems with the generation later on.
I will fix to avoid this validation error messages in future.

**Comment by jadelkhoury** [comment]
closed by https://github.com/eclipse/lyo.designer/pull/248
